
platform:ios, '8.0'


target 'TextGit' do


pod 'MJExtension'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'KDCycleBannerView'#轮播图
#pod 'IQKeyboardManager', '3.3.7'
pod 'Masonry'
#pod 'ReactiveCocoa'

pod 'YYKit'
pod 'AFNetworking'

#pod 'SSToolKit'

pod 'GPUImage'





end
